### ISSUE TITLE
 Please release 0.3.0 or 0.2.10;  current released version 0.2.9 does not work on update-dryrun for the egress definition part.

### ISSUE THREAD

**Issue by Yuki-Inoue** [codenize-tools/piculet#36]
Current latest released version for piculet is 0.2.9.  Currently, this version has problem in at least for update-dryrun.  Namely, if security group had `egress` definition, it results in error:

```
/Users/an_user/.rbenv/versions/2.4.4/lib/ruby/gems/2.4.0/gems/piculet-0.2.9/lib/piculet/client.rb:175:in `walk_security_group': Piculet::EC2Wrapper::SecurityGroupCollection::SecurityGroup#vpc? at /Users/an_user/.rbenv/versions/2.4.4/lib/ruby/2.4.0/forwardable.rb:157 forwarding to private method OpenStruct#vpc?
```

This problem is fixed on the commit of 168c795 , but it is only released as the pre-release versions.  I think this situation is not desirable.  So:

* May I ask if is it possible to release current 0.3.0 branch as version 0.3.0 or 0.2.10?

**Comment by aibou** [comment]
Sorry for late response.
It sounds good to me. @winebarrel how about you? If its ok with you, I'll build & push gem to RubyGems :)

**Comment by aibou** [comment]
@Yuki-Inoue sorry for making you wait. Yesterday I have pushed the gem with v0.3.0.
We appriciate your opinion!
